### ISSUE TITLE
create a method to block repetitive deck cards 

### ISSUE THREAD

**Issue by leo064** [leo064/full-truco#1]

**Comment by leo064** [comment]
maybe something like a: 

    first_card = turn_cards[0]
    second_card = turn_cards[1]   
    for x in range(turn_cards[0]):
        for y in range(turn_cards[1]):
            while x == y:
                for z in range(0, 2):
                    suit = random.randrange(1, 4)
                    number = random.randrange(1, 13)
                    show = suit, number
                    turn_cards.insert(z, show)

but, return a TypeError: 
... ... ...
-> for x in range(turn_cards[0]):
TypeError: 'tuple' object cannot be interpreted as an integer

**Comment by AliHaider20** [comment]
Where do you want to apply the above logic?
Can you share the full code where you're getting this error?

**Comment by leo064** [comment]
I need some logic to block repetitive cards that have been randomized in method:

    def take_turncards():
    """function to take the 12 random cards. + side card"""
    turn_cards = []
    for numcard in range(1, 14):
        suit = random.randrange(1, 4)
        number = random.randrange(1, 11)
        shownum = suit, number
        turn_numcards.append(shownum)
        
        if number == 8: number_name = "Q"
        elif number == 9: number_name = "J"
        elif number == 10: number_name = "K"
        else: number_name = number
        
        if suit == 0: suit_name = 'clubs'
        elif suit == 1: suit_name = 'hearts'
        elif suit == 2: suit_name = 'spades'
        else: suit_name = 'diamonds'

        show = suit_name, number_name
        turn_cards.append(show)
    return turn_cards


return: 
[(6, 'diamonds'), (2, 'spades'), (2, 'spades')]
[(4, 'spades'), (3, 'hearts'), (3, 'hearts')]
[(7, 'spades'), (2, 'spades'), ('J', 'spades')]
[(5, 'spades'), ('J', 'diamonds'), ('K', 'diamonds')]
side is ... (1, 'spades')

2 of spades repeat three times, I need to solve this

**Comment by leo064** [comment]
in first comment, i show the logic that I tred to use to solve this.
i utilized something like a "List Comprehensions", combined two lists (turncards [0] and turncards [1]), and randomized if they cards it equal. but, no effects.
the logical is minimally correct? Could I go anywhere with this?

**Comment by AliHaider20** [comment]
import random
def take_turncards():
   """function to take the 12 random cards. + side card"""
   turn_cards = []
   for numcard in range(1, 14):
      suit = random.randrange(1, 4)
      number = random.randrange(1, 11)
      shownum = suit, number
      if shownum in turn_cards:
          continue
      else:
         turn_cards.append(shownum)
         if number == 8: number_name = "Q"
         elif number == 9: number_name = "J"
         elif number == 10: number_name = "K"
         else: number_name = number
          
         if suit == 0: suit_name = 'clubs'
         elif suit == 1: suit_name = 'hearts'
         elif suit == 2: suit_name = 'spades'
         else: suit_name = 'diamonds'

         show = suit_name, number_name
         turn_cards.append(show)
   return turn_cards

print(take_turncards())


O/P:

[(1, 5), ('hearts', 5), (2, 2), ('spades', 2), (3, 6), ('diamonds', 6), 
(1, 10), ('hearts', 'K'), (3, 8), ('diamonds', 'Q'), (3, 9), ('diamonds', 'J'),
 (1, 6), ('hearts', 6), (1, 7), ('hearts', 7), (1, 3), ('hearts', 3), (3, 10),
 ('diamonds', 'K'), (2, 5), ('spades', 5)]

**Comment by leo064** [comment]
Solution Simple and gracefully. Thank you!

**Comment by AliHaider20** [comment]
Thanks. Feeling great.
